VERSION_AND_PATH:
  ROOT_PATH: ""
  ARTIFACTS_PATH: ""
  SUPERVISION_VERSION: "0.6.0"
  SAM_ENCODER_VERSION: "vit_h" # do not change
  SAM_CHECKPOINT_PATH: # if empty, will automatically loaded from config loader
  GROUNDING_DINO_CONFIG_PATH: # if empty, will automatically loaded from config loader
  GROUNDING_DINO_CHECKPOINT_PATH: # if empty, will automatically loaded from config loader

YOLO:
  YOLO_CHECKPOINT_PATH:

CLIP:
  CLIP_MODEL: "ViT-B/32" #ViT-L/14
