defaults:
  - node: constrained_video
  - video_processor: real_video
  - vision_percepter: single_vision_percepter
  - automaton: drtmc
  - model: default
  - override hydra/launcher: local
  - override hydra/output: local
  - _self_

hydra:
  job:
    chdir: True

ns_vfs_system_cfg:
  # if None, the result will not be saved
  save_result_dir: /opt/Neuro-Symbolic-Video-Frame-Search/output
  model_checker:
    is_filter: False
    verbose: False
  constrained_video_streaming:
    property_constrained: True
    filter_type: blur

video_file_path: '/opt/Neuro-Symbolic-Video-Frame-Search/sample_data/av2.mp4'
ltl_formula: 'P>=0.80 G [~person & ~car]'
proposition_set:
  - person
  - car

