defaults:
  - node: default
  - video_processor: tlv_dataset
  - vision_percepter: single_vision_percepter
  - model: default
  - override hydra/launcher: local
  - override hydra/output: local
  - _self_

hydra:
  job:
    chdir: True

video_file_path: '/opt/Neuro-Symbolic-Video-Frame-Search/sample_data/ouputs/benchmark_ImageNet2017-1K_ltl_"stop_sign" U "sheep"_5_0.pkl'
ltl_formula: 
proposition_set:
  #- Proposition 1
  #- Proposition 2