defaults:
  - node: default
  - video_processor: real_video
  - vision_percepter: single_vision_percepter
  - automaton: probabilistic
  - model: default
  - override hydra/launcher: local
  - override hydra/output: local
  - _self_

hydra:
  job:
    chdir: True

ns_vfs_system_cfg:
  save_result_dir: /opt/Neuro-Symbolic-Video-Frame-Search/_dev/tri/result
  model_checker:
    is_filter: False
    verbose: False

video_file_path: /opt/Neuro-Symbolic-Video-Frame-Search/_dev/tri/tri.mp4
ltl_formula: '"car" U "truck"'
proposition_set:
  - "car"
  - "truck"