defaults:
  - node: tlv_dataset
  - video_processor: tlv_dataset
  - vision_percepter: single_vision_percepter
  - automaton: probabilistic
  - model: default
  - override hydra/launcher: local
  - override hydra/output: local
  - _self_

hydra:
  job:
    chdir: True

ns_vfs_system_cfg:
  # if None, the result will not be saved
  save_result_dir: 
  model_checker:
    is_filter: False
    verbose: False

video_file_path: # your tlv video file path
ltl_formula: # your LTL formula
proposition_set:
  #- Proposition 1
  #- Proposition 2