[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["ns_vfs"]  # package names should match these glob patterns (["*"] by default)
exclude = ["store", "artifacts, docker, experiments"]  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)

[tool.my-tool]
submodule_path = "ns_vfs/model/diffusion/stable_diffusion"

[project]
name = "ns-vfs"
version = "0.0.1"
authors = [
  { name="Minkyu Choi", email="minkyu.choi@utexas.edu" },
]
description = "The pipeline to convert video to automaton"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "omegaconf",
    "hydra-core>=1.2.0",
    "numpy==1.21.5",
    "pandas",
    "sympy",
    "regex",
    "supervision==0.6.0",
    "roboflow",
    "einops",
    "pytorch-lightning==1.4.2",
    "torchmetrics==0.5",
    "ultralytics",
    "clip@git+https://github.com/openai/CLIP.git",
]
[tool.black]
line-length = 80

[project.urls]
"Homepage" = "https://github.com/UTAustin-SwarmLab/Video-to-Automaton"
"Bug Tracker" = "https://github.com/UTAustin-SwarmLab/Video-to-Automaton"

[project.optional-dependencies]
dev = ["black", "ruff", "mypy"]
test = ["pytest", "pytest-cov", "pytest-mock"]

