_target_: ns_vfs.percepter.multi_vision_percepter.MultiVisionPercepter
cv_models: 
  yolo:
    _target_: ns_vfs.model.vision.object_detection.yolo.Yolo
    weight_path: ${model.vision.yolo.weight_path}
    gpu_number: ${model.vision.yolo.gpu_number}
    
  clip:
    _target_: ns_vfs.model.vision.object_detection.clip_model.ClipPerception
    model_name: ${model.vision.clip.model_name}
    gpu_device: ${model.vision.clip.gpu_device}
