name: Default CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ."[dev, test]"
      - name: Prepare environment
        id: set-matrix
        run: echo "::set-output name=matrix::${{ toJson(github.ref) }}"

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Tests
        run: |
          python -m pip install --upgrade pip
          pip install -e ."[test]"
          python -m pytest tests/