name: Ruff
on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Run Ruff with auto-fix
      uses: chartboost/ruff-action@v1
      with:
        args: --fix  # Automatically apply safe fixes
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'style fixes by ruff'
        file_pattern: '*.py'  # Ensure only Python files are committed
